defmodule Caredeck.Repo.Migrations.InstallRelatives do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:residents) do
      remove :state
    end

    create table(:relatives_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :facility_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:relatives_of_residents_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :facility_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:relatives_of_residents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:relatives_of_residents_versions) do
      modify :version_source_id,
             references(:relatives_of_residents,
               column: :id,
               name: "relatives_of_residents_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:relatives_of_residents) do
      add :facility_id,
          references(:facilities,
            column: :id,
            name: "relatives_of_residents_facility_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :resident_id,
          references(:residents,
            column: :id,
            name: "relatives_of_residents_resident_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :relative_id, :uuid, null: false
      add :relationship, :text, null: false
      add :is_primary_contact, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:relatives_of_residents, [:facility_id, :resident_id, :relative_id],
             name: "relatives_of_residents_unique_link_index"
           )

    create table(:relatives, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:relatives_versions) do
      modify :version_source_id,
             references(:relatives,
               column: :id,
               name: "relatives_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:relatives_of_residents) do
      modify :relative_id,
             references(:relatives,
               column: :id,
               name: "relatives_of_residents_relative_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:relatives) do
      add :facility_id,
          references(:facilities,
            column: :id,
            name: "relatives_facility_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "relatives_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :display_name, :text
      add :phone, :text
      add :avatar_url, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:relatives, [:facility_id, :user_id],
             name: "relatives_unique_user_per_facility_index"
           )
  end

  def down do
    drop constraint(:relatives, "relatives_facility_id_fkey")

    drop constraint(:relatives, "relatives_user_id_fkey")

    drop_if_exists unique_index(:relatives, [:facility_id, :user_id],
                     name: "relatives_unique_user_per_facility_index"
                   )

    alter table(:relatives) do
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :avatar_url
      remove :phone
      remove :display_name
      remove :user_id
      remove :facility_id
    end

    drop constraint(:relatives_of_residents, "relatives_of_residents_relative_id_fkey")

    alter table(:relatives_of_residents) do
      modify :relative_id, :uuid
    end

    drop constraint(:relatives_versions, "relatives_versions_version_source_id_fkey")

    alter table(:relatives_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:relatives)

    drop constraint(:relatives_of_residents, "relatives_of_residents_facility_id_fkey")

    drop constraint(:relatives_of_residents, "relatives_of_residents_resident_id_fkey")

    drop_if_exists unique_index(
                     :relatives_of_residents,
                     [:facility_id, :resident_id, :relative_id],
                     name: "relatives_of_residents_unique_link_index"
                   )

    alter table(:relatives_of_residents) do
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :is_primary_contact
      remove :relationship
      remove :relative_id
      remove :resident_id
      remove :facility_id
    end

    drop constraint(
           :relatives_of_residents_versions,
           "relatives_of_residents_versions_version_source_id_fkey"
         )

    alter table(:relatives_of_residents_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:relatives_of_residents)

    drop table(:relatives_of_residents_versions)

    drop table(:relatives_versions)

    alter table(:residents) do
      add :state, :text, null: false, default: "admitted"
    end
  end
end
