defmodule Caredeck.Repo.Migrations.InstallResidents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:residents_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:residents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:residents_versions) do
      modify :version_source_id,
             references(:residents,
               column: :id,
               name: "residents_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:residents) do
      add :facility_id,
          references(:facilities,
            column: :id,
            name: "residents_facility_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :first_name, :text, null: false
      add :last_name, :text, null: false
      add :date_of_birth, :date
      add :avatar_url, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end
  end

  def down do
    drop constraint(:residents, "residents_facility_id_fkey")

    alter table(:residents) do
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :avatar_url
      remove :date_of_birth
      remove :last_name
      remove :first_name
      remove :facility_id
    end

    drop constraint(:residents_versions, "residents_versions_version_source_id_fkey")

    alter table(:residents_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:residents)

    drop table(:residents_versions)
  end
end
