defmodule Caredeck.Repo.Migrations.InstallAttachments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:attachments_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :facility_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:attachments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:attachments_versions) do
      modify :version_source_id,
             references(:attachments,
               column: :id,
               name: "attachments_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:attachments) do
      add :facility_id,
          references(:facilities,
            column: :id,
            name: "attachments_facility_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :post_id,
          references(:posts,
            column: :id,
            name: "attachments_post_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :kind, :text, null: false
      add :s3_key, :text, null: false
      add :thumbnail_s3_key, :text
      add :mime_type, :text
      add :bytes, :bigint
      add :duration_sec, :bigint
      add :caption, :text
      add :position, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end
  end

  def down do
    drop constraint(:attachments, "attachments_facility_id_fkey")

    drop constraint(:attachments, "attachments_post_id_fkey")

    alter table(:attachments) do
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :position
      remove :caption
      remove :duration_sec
      remove :bytes
      remove :mime_type
      remove :thumbnail_s3_key
      remove :s3_key
      remove :kind
      remove :post_id
      remove :facility_id
    end

    drop constraint(:attachments_versions, "attachments_versions_version_source_id_fkey")

    alter table(:attachments_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:attachments)

    drop table(:attachments_versions)
  end
end
