defmodule Caredeck.Repo.Migrations.InstallFeedPostAndAudience do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:posts_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :facility_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:posts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:posts_versions) do
      modify :version_source_id,
             references(:posts,
               column: :id,
               name: "posts_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:posts) do
      add :facility_id,
          references(:facilities,
            column: :id,
            name: "posts_facility_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :team_identity_id,
          references(:team_identities,
            column: :id,
            name: "posts_team_identity_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :body, :text, null: false
      add :is_internal, :boolean, default: false
      add :published_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      add :edited_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create table(:post_audiences_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :facility_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:post_audiences, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:post_audiences_versions) do
      modify :version_source_id,
             references(:post_audiences,
               column: :id,
               name: "post_audiences_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:post_audiences) do
      add :facility_id,
          references(:facilities,
            column: :id,
            name: "post_audiences_facility_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :post_id,
          references(:posts,
            column: :id,
            name: "post_audiences_post_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :resident_id,
          references(:residents,
            column: :id,
            name: "post_audiences_resident_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:post_audiences, [:facility_id, :post_id, :resident_id],
             name: "post_audiences_unique_post_resident_index"
           )
  end

  def down do
    drop constraint(:post_audiences, "post_audiences_facility_id_fkey")

    drop constraint(:post_audiences, "post_audiences_post_id_fkey")

    drop constraint(:post_audiences, "post_audiences_resident_id_fkey")

    drop_if_exists unique_index(:post_audiences, [:facility_id, :post_id, :resident_id],
                     name: "post_audiences_unique_post_resident_index"
                   )

    alter table(:post_audiences) do
      remove :archived_at
      remove :inserted_at
      remove :resident_id
      remove :post_id
      remove :facility_id
    end

    drop constraint(:post_audiences_versions, "post_audiences_versions_version_source_id_fkey")

    alter table(:post_audiences_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:post_audiences)

    drop table(:post_audiences_versions)

    drop constraint(:posts, "posts_facility_id_fkey")

    drop constraint(:posts, "posts_team_identity_id_fkey")

    alter table(:posts) do
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :edited_at
      remove :published_at
      remove :is_internal
      remove :body
      remove :team_identity_id
      remove :facility_id
    end

    drop constraint(:posts_versions, "posts_versions_version_source_id_fkey")

    alter table(:posts_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:posts)

    drop table(:posts_versions)
  end
end
