defmodule Caredeck.Repo.Migrations.InstallAidDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:aid_applications, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :facility_id,
          references(:facilities,
            column: :id,
            name: "aid_applications_facility_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :resident_id,
          references(:residents,
            column: :id,
            name: "aid_applications_resident_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :applicant_user_id,
          references(:users,
            column: :id,
            name: "aid_applications_applicant_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :applicant_team_id,
          references(:team_identities,
            column: :id,
            name: "aid_applications_applicant_team_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :state, :text, null: false, default: "draft"
      add :submitted_at, :utc_datetime_usec
      add :decided_at, :utc_datetime_usec
      add :outcome, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create table(:aid_application_sections_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :facility_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:aid_applications_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :facility_id, :uuid, null: false

      add :version_source_id,
          references(:aid_applications,
            column: :id,
            name: "aid_applications_versions_version_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:aid_application_sections, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:aid_application_sections_versions) do
      modify :version_source_id,
             references(:aid_application_sections,
               column: :id,
               name: "aid_application_sections_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:aid_application_sections) do
      add :facility_id,
          references(:facilities,
            column: :id,
            name: "aid_application_sections_facility_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :application_id,
          references(:aid_applications,
            column: :id,
            name: "aid_application_sections_application_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :section_key, :text, null: false
      add :position, :bigint, null: false
      add :status, :text, null: false, default: "not_started"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:aid_application_sections, [:facility_id, :application_id, :section_key],
             name: "aid_application_sections_one_per_section_per_application_index"
           )
  end

  def down do
    drop constraint(:aid_application_sections, "aid_application_sections_facility_id_fkey")

    drop constraint(:aid_application_sections, "aid_application_sections_application_id_fkey")

    drop_if_exists unique_index(
                     :aid_application_sections,
                     [:facility_id, :application_id, :section_key],
                     name: "aid_application_sections_one_per_section_per_application_index"
                   )

    alter table(:aid_application_sections) do
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :status
      remove :position
      remove :section_key
      remove :application_id
      remove :facility_id
    end

    drop constraint(
           :aid_application_sections_versions,
           "aid_application_sections_versions_version_source_id_fkey"
         )

    alter table(:aid_application_sections_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:aid_application_sections)

    drop constraint(
           :aid_applications_versions,
           "aid_applications_versions_version_source_id_fkey"
         )

    drop table(:aid_applications_versions)

    drop table(:aid_application_sections_versions)

    drop constraint(:aid_applications, "aid_applications_facility_id_fkey")

    drop constraint(:aid_applications, "aid_applications_resident_id_fkey")

    drop constraint(:aid_applications, "aid_applications_applicant_user_id_fkey")

    drop constraint(:aid_applications, "aid_applications_applicant_team_id_fkey")

    drop table(:aid_applications)
  end
end
