defmodule Caredeck.Repo.Migrations.AddResidentLifecycle do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:residents) do
      add :birth_name, :text
      add :lifecycle_state, :text, null: false, default: "admitted"
      add :admitted_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      add :discharged_at, :utc_datetime_usec
      add :deceased_at, :utc_datetime_usec
      add :state, :text, null: false, default: "admitted"

      add :ward_id,
          references(:wards,
            column: :id,
            name: "residents_ward_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:residents, "residents_ward_id_fkey")

    alter table(:residents) do
      remove :ward_id
      remove :state
      remove :deceased_at
      remove :discharged_at
      remove :admitted_at
      remove :lifecycle_state
      remove :birth_name
    end
  end
end
