defmodule Caredeck.Repo.Migrations.InstallCaregiverProfile do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:caregiver_profiles_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :facility_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:caregiver_profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:caregiver_profiles_versions) do
      modify :version_source_id,
             references(:caregiver_profiles,
               column: :id,
               name: "caregiver_profiles_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:caregiver_profiles) do
      add :facility_id,
          references(:facilities,
            column: :id,
            name: "caregiver_profiles_facility_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "caregiver_profiles_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :display_name, :text, null: false
      add :role_label, :text
      add :avatar_url, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:caregiver_profiles, [:facility_id, :user_id],
             name: "caregiver_profiles_unique_caregiver_per_facility_index"
           )
  end

  def down do
    drop constraint(:caregiver_profiles, "caregiver_profiles_facility_id_fkey")

    drop constraint(:caregiver_profiles, "caregiver_profiles_user_id_fkey")

    drop_if_exists unique_index(:caregiver_profiles, [:facility_id, :user_id],
                     name: "caregiver_profiles_unique_caregiver_per_facility_index"
                   )

    alter table(:caregiver_profiles) do
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :avatar_url
      remove :role_label
      remove :display_name
      remove :user_id
      remove :facility_id
    end

    drop constraint(
           :caregiver_profiles_versions,
           "caregiver_profiles_versions_version_source_id_fkey"
         )

    alter table(:caregiver_profiles_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:caregiver_profiles)

    drop table(:caregiver_profiles_versions)
  end
end
