defmodule Caredeck.Repo.Migrations.AddFormfixApplicationOnePerResident do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    WITH ranked AS (
      SELECT
        id,
        ROW_NUMBER() OVER (
          PARTITION BY facility_id, resident_id
          ORDER BY inserted_at ASC, id ASC
        ) AS rn
      FROM formfix_applications
    ),
    dupes AS (SELECT id FROM ranked WHERE rn > 1)
    DELETE FROM formfix_applications_versions
    WHERE version_source_id IN (SELECT id FROM dupes)
    """)

    execute("""
    WITH ranked AS (
      SELECT
        id,
        ROW_NUMBER() OVER (
          PARTITION BY facility_id, resident_id
          ORDER BY inserted_at ASC, id ASC
        ) AS rn
      FROM formfix_applications
    )
    DELETE FROM formfix_applications
    WHERE id IN (SELECT id FROM ranked WHERE rn > 1)
    """)

    create unique_index(:formfix_applications, [:facility_id, :resident_id],
             name: "formfix_applications_one_per_resident_index"
           )
  end

  def down do
    drop_if_exists unique_index(:formfix_applications, [:facility_id, :resident_id],
                     name: "formfix_applications_one_per_resident_index"
                   )
  end
end
