defmodule Caredeck.Repo.Migrations.InstallCommentsReactionsTags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:resident_tags_on_posts_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :facility_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:resident_tags_on_posts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:resident_tags_on_posts_versions) do
      modify :version_source_id,
             references(:resident_tags_on_posts,
               column: :id,
               name: "resident_tags_on_posts_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:resident_tags_on_posts) do
      add :facility_id,
          references(:facilities,
            column: :id,
            name: "resident_tags_on_posts_facility_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :post_id,
          references(:posts,
            column: :id,
            name: "resident_tags_on_posts_post_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :resident_id,
          references(:residents,
            column: :id,
            name: "resident_tags_on_posts_resident_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:resident_tags_on_posts, [:facility_id, :post_id, :resident_id],
             name: "resident_tags_on_posts_unique_tag_index"
           )

    create table(:reactions_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :facility_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:reactions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:reactions_versions) do
      modify :version_source_id,
             references(:reactions,
               column: :id,
               name: "reactions_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:reactions) do
      add :facility_id,
          references(:facilities,
            column: :id,
            name: "reactions_facility_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :post_id,
          references(:posts,
            column: :id,
            name: "reactions_post_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "reactions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :kind, :text, null: false, default: "like"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:reactions, [:facility_id, :post_id, :user_id],
             name: "reactions_one_reaction_per_user_per_post_index"
           )

    create table(:comments_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :facility_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:comments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:comments_versions) do
      modify :version_source_id,
             references(:comments,
               column: :id,
               name: "comments_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:comments) do
      add :facility_id,
          references(:facilities,
            column: :id,
            name: "comments_facility_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :post_id,
          references(:posts,
            column: :id,
            name: "comments_post_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :author_user_id,
          references(:users,
            column: :id,
            name: "comments_author_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :body, :text, null: false
      add :edited_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end
  end

  def down do
    drop constraint(:comments, "comments_facility_id_fkey")

    drop constraint(:comments, "comments_post_id_fkey")

    drop constraint(:comments, "comments_author_user_id_fkey")

    alter table(:comments) do
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :edited_at
      remove :body
      remove :author_user_id
      remove :post_id
      remove :facility_id
    end

    drop constraint(:comments_versions, "comments_versions_version_source_id_fkey")

    alter table(:comments_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:comments)

    drop table(:comments_versions)

    drop constraint(:reactions, "reactions_facility_id_fkey")

    drop constraint(:reactions, "reactions_post_id_fkey")

    drop constraint(:reactions, "reactions_user_id_fkey")

    drop_if_exists unique_index(:reactions, [:facility_id, :post_id, :user_id],
                     name: "reactions_one_reaction_per_user_per_post_index"
                   )

    alter table(:reactions) do
      remove :archived_at
      remove :inserted_at
      remove :kind
      remove :user_id
      remove :post_id
      remove :facility_id
    end

    drop constraint(:reactions_versions, "reactions_versions_version_source_id_fkey")

    alter table(:reactions_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:reactions)

    drop table(:reactions_versions)

    drop constraint(:resident_tags_on_posts, "resident_tags_on_posts_facility_id_fkey")

    drop constraint(:resident_tags_on_posts, "resident_tags_on_posts_post_id_fkey")

    drop constraint(:resident_tags_on_posts, "resident_tags_on_posts_resident_id_fkey")

    drop_if_exists unique_index(:resident_tags_on_posts, [:facility_id, :post_id, :resident_id],
                     name: "resident_tags_on_posts_unique_tag_index"
                   )

    alter table(:resident_tags_on_posts) do
      remove :archived_at
      remove :inserted_at
      remove :resident_id
      remove :post_id
      remove :facility_id
    end

    drop constraint(
           :resident_tags_on_posts_versions,
           "resident_tags_on_posts_versions_version_source_id_fkey"
         )

    alter table(:resident_tags_on_posts_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:resident_tags_on_posts)

    drop table(:resident_tags_on_posts_versions)
  end
end
