defmodule Caredeck.Repo.Migrations.AddUploadedDocuments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:aid_uploaded_documents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :facility_id,
          references(:facilities,
            column: :id,
            name: "aid_uploaded_documents_facility_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :application_id,
          references(:aid_applications,
            column: :id,
            name: "aid_uploaded_documents_application_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :section_key, :text, null: false
      add :document_key, :text, null: false
      add :s3_key, :text, null: false
      add :original_filename, :text
      add :bytes, :bigint
      add :mime_type, :text
      add :verified_at, :utc_datetime_usec
      add :state, :text, null: false, default: "pending"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(
             :aid_uploaded_documents,
             [:facility_id, :application_id, :section_key, :document_key, :s3_key],
             name: "aid_uploaded_documents_no_duplicate_upload_index"
           )

    create table(:aid_uploaded_documents_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :facility_id, :uuid, null: false

      add :version_source_id,
          references(:aid_uploaded_documents,
            column: :id,
            name: "aid_uploaded_documents_versions_version_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(
           :aid_uploaded_documents_versions,
           "aid_uploaded_documents_versions_version_source_id_fkey"
         )

    drop table(:aid_uploaded_documents_versions)

    drop constraint(:aid_uploaded_documents, "aid_uploaded_documents_facility_id_fkey")

    drop constraint(:aid_uploaded_documents, "aid_uploaded_documents_application_id_fkey")

    drop_if_exists unique_index(
                     :aid_uploaded_documents,
                     [:facility_id, :application_id, :section_key, :document_key, :s3_key],
                     name: "aid_uploaded_documents_no_duplicate_upload_index"
                   )

    drop table(:aid_uploaded_documents)
  end
end
