defmodule Caredeck.Repo.Migrations.AddFormfixApplicationOnePerResident do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    CREATE TEMP TABLE dupe_app_ids AS
    WITH ranked AS (
      SELECT
        id,
        ROW_NUMBER() OVER (
          PARTITION BY facility_id, resident_id
          ORDER BY inserted_at ASC, id ASC
        ) AS rn
      FROM formfix_applications
    )
    SELECT id FROM ranked WHERE rn > 1
    """)

    execute("""
    DELETE FROM formfix_application_sections_versions
    WHERE version_source_id IN (
      SELECT id FROM formfix_application_sections
      WHERE application_id IN (SELECT id FROM dupe_app_ids)
    )
    """)

    execute("""
    DELETE FROM formfix_section_answers_versions
    WHERE version_source_id IN (
      SELECT id FROM formfix_section_answers
      WHERE application_id IN (SELECT id FROM dupe_app_ids)
    )
    """)

    execute("""
    DELETE FROM formfix_uploaded_documents_versions
    WHERE version_source_id IN (
      SELECT id FROM formfix_uploaded_documents
      WHERE application_id IN (SELECT id FROM dupe_app_ids)
    )
    """)

    execute("""
    DELETE FROM formfix_application_notes_versions
    WHERE version_source_id IN (
      SELECT id FROM formfix_application_notes
      WHERE application_id IN (SELECT id FROM dupe_app_ids)
    )
    """)

    execute("""
    DELETE FROM formfix_applications_versions
    WHERE version_source_id IN (SELECT id FROM dupe_app_ids)
    """)

    execute("""
    DELETE FROM formfix_applications
    WHERE id IN (SELECT id FROM dupe_app_ids)
    """)

    execute("DROP TABLE dupe_app_ids")

    create unique_index(:formfix_applications, [:facility_id, :resident_id],
             name: "formfix_applications_one_per_resident_index"
           )
  end

  def down do
    drop_if_exists unique_index(:formfix_applications, [:facility_id, :resident_id],
                     name: "formfix_applications_one_per_resident_index"
                   )
  end
end
