defmodule Caredeck.Repo.Migrations.InstallUserPasskeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_passkeys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "user_passkeys_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :credential_id, :binary, null: false
      add :public_key, :binary, null: false
      add :sign_count, :bigint, default: 0
      add :aaguid, :text
      add :nickname, :text
      add :last_used_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:user_passkeys, [:credential_id],
             name: "user_passkeys_unique_credential_index"
           )
  end

  def down do
    drop constraint(:user_passkeys, "user_passkeys_user_id_fkey")

    drop_if_exists unique_index(:user_passkeys, [:credential_id],
                     name: "user_passkeys_unique_credential_index"
                   )

    drop table(:user_passkeys)
  end
end
