defmodule Caredeck.Repo.Migrations.InstallKitchenDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:kitchen_menu_template_slots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :facility_id,
          references(:facilities,
            column: :id,
            name: "kitchen_menu_template_slots_facility_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :menu_template_id, :uuid, null: false
      add :day_of_week, :text, null: false
      add :category, :text, null: false
      add :product_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(
             :kitchen_menu_template_slots,
             [:facility_id, :menu_template_id, :day_of_week, :category],
             name: "kitchen_menu_template_slots_unique_slot_index"
           )

    create table(:kitchen_menu_templates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:kitchen_menu_template_slots) do
      modify :menu_template_id,
             references(:kitchen_menu_templates,
               column: :id,
               name: "kitchen_menu_template_slots_menu_template_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:kitchen_menu_templates) do
      add :facility_id,
          references(:facilities,
            column: :id,
            name: "kitchen_menu_templates_facility_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :name, :text, null: false
      add :is_active, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:kitchen_menu_templates, [:facility_id],
             name: "kitchen_menu_templates_one_active_per_facility_index",
             where: "(is_active = TRUE)"
           )

    create table(:kitchen_resident_diet_profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :facility_id,
          references(:facilities,
            column: :id,
            name: "kitchen_resident_diet_profiles_facility_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :resident_id,
          references(:residents,
            column: :id,
            name: "kitchen_resident_diet_profiles_resident_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :allergens, {:array, :text}, default: []
      add :preferences, {:array, :text}, default: []
      add :skip_categories, {:array, :text}, default: []
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:kitchen_resident_diet_profiles, [:facility_id, :resident_id],
             name: "kitchen_resident_diet_profiles_unique_resident_profile_index"
           )

    create table(:kitchen_products, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:kitchen_menu_template_slots) do
      modify :product_id,
             references(:kitchen_products,
               column: :id,
               name: "kitchen_menu_template_slots_product_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:kitchen_products) do
      add :facility_id,
          references(:facilities,
            column: :id,
            name: "kitchen_products_facility_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :name, :text, null: false
      add :category, :text, null: false
      add :allergens, {:array, :text}, default: []
      add :kcal, :bigint
      add :is_default, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:kitchen_products, [:facility_id, :category, :name],
             name: "kitchen_products_unique_name_per_facility_per_category_index"
           )

    create table(:kitchen_menu_templates_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :facility_id, :uuid, null: false

      add :version_source_id,
          references(:kitchen_menu_templates,
            column: :id,
            name: "kitchen_menu_templates_versions_version_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:kitchen_products_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :facility_id, :uuid, null: false

      add :version_source_id,
          references(:kitchen_products,
            column: :id,
            name: "kitchen_products_versions_version_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:kitchen_resident_diet_profiles_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :facility_id, :uuid, null: false

      add :version_source_id,
          references(:kitchen_resident_diet_profiles,
            column: :id,
            name: "kitchen_resident_diet_profiles_versions_version_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:kitchen_day_menus_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :facility_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:kitchen_day_menu_slots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :facility_id,
          references(:facilities,
            column: :id,
            name: "kitchen_day_menu_slots_facility_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :day_menu_id, :uuid, null: false
      add :category, :text, null: false
      add :product_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:kitchen_day_menu_slots, [:facility_id, :day_menu_id, :category],
             name: "kitchen_day_menu_slots_unique_slot_index"
           )

    create table(:kitchen_day_menu_slots_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :facility_id, :uuid, null: false

      add :version_source_id,
          references(:kitchen_day_menu_slots,
            column: :id,
            name: "kitchen_day_menu_slots_versions_version_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:kitchen_day_menus, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:kitchen_day_menus_versions) do
      modify :version_source_id,
             references(:kitchen_day_menus,
               column: :id,
               name: "kitchen_day_menus_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:kitchen_day_menu_slots) do
      modify :day_menu_id,
             references(:kitchen_day_menus,
               column: :id,
               name: "kitchen_day_menu_slots_day_menu_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :product_id,
             references(:kitchen_products,
               column: :id,
               name: "kitchen_day_menu_slots_product_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:kitchen_day_menus) do
      add :facility_id,
          references(:facilities,
            column: :id,
            name: "kitchen_day_menus_facility_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :date, :date, null: false
      add :notes, :text
      add :materialised_from_template_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:kitchen_day_menus, [:facility_id, :date],
             name: "kitchen_day_menus_unique_facility_date_index"
           )

    create table(:kitchen_resident_meal_orders, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :facility_id,
          references(:facilities,
            column: :id,
            name: "kitchen_resident_meal_orders_facility_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :resident_id,
          references(:residents,
            column: :id,
            name: "kitchen_resident_meal_orders_resident_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :date, :date, null: false
      add :category, :text, null: false

      add :product_id,
          references(:kitchen_products,
            column: :id,
            name: "kitchen_resident_meal_orders_product_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :state, :text, null: false, default: "ordered"
      add :ordered_by_user_id, :uuid
      add :ordered_by_team_id, :uuid
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(
             :kitchen_resident_meal_orders,
             [:facility_id, :resident_id, :date, :category],
             name:
               "kitchen_resident_meal_orders_one_order_per_resident_per_date_per_category_index"
           )

    create table(:kitchen_menu_template_slots_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :facility_id, :uuid, null: false

      add :version_source_id,
          references(:kitchen_menu_template_slots,
            column: :id,
            name: "kitchen_menu_template_slots_versions_version_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:kitchen_resident_meal_orders_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :facility_id, :uuid, null: false

      add :version_source_id,
          references(:kitchen_resident_meal_orders,
            column: :id,
            name: "kitchen_resident_meal_orders_versions_version_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(
           :kitchen_resident_meal_orders_versions,
           "kitchen_resident_meal_orders_versions_version_source_id_fkey"
         )

    drop table(:kitchen_resident_meal_orders_versions)

    drop constraint(
           :kitchen_menu_template_slots_versions,
           "kitchen_menu_template_slots_versions_version_source_id_fkey"
         )

    drop table(:kitchen_menu_template_slots_versions)

    drop constraint(
           :kitchen_resident_meal_orders,
           "kitchen_resident_meal_orders_facility_id_fkey"
         )

    drop constraint(
           :kitchen_resident_meal_orders,
           "kitchen_resident_meal_orders_resident_id_fkey"
         )

    drop constraint(:kitchen_resident_meal_orders, "kitchen_resident_meal_orders_product_id_fkey")

    drop_if_exists unique_index(
                     :kitchen_resident_meal_orders,
                     [:facility_id, :resident_id, :date, :category],
                     name:
                       "kitchen_resident_meal_orders_one_order_per_resident_per_date_per_category_index"
                   )

    drop table(:kitchen_resident_meal_orders)

    drop constraint(:kitchen_day_menus, "kitchen_day_menus_facility_id_fkey")

    drop_if_exists unique_index(:kitchen_day_menus, [:facility_id, :date],
                     name: "kitchen_day_menus_unique_facility_date_index"
                   )

    alter table(:kitchen_day_menus) do
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :materialised_from_template_id
      remove :notes
      remove :date
      remove :facility_id
    end

    drop constraint(:kitchen_day_menu_slots, "kitchen_day_menu_slots_day_menu_id_fkey")

    drop constraint(:kitchen_day_menu_slots, "kitchen_day_menu_slots_product_id_fkey")

    alter table(:kitchen_day_menu_slots) do
      modify :product_id, :uuid
      modify :day_menu_id, :uuid
    end

    drop constraint(
           :kitchen_day_menus_versions,
           "kitchen_day_menus_versions_version_source_id_fkey"
         )

    alter table(:kitchen_day_menus_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:kitchen_day_menus)

    drop constraint(
           :kitchen_day_menu_slots_versions,
           "kitchen_day_menu_slots_versions_version_source_id_fkey"
         )

    drop table(:kitchen_day_menu_slots_versions)

    drop constraint(:kitchen_day_menu_slots, "kitchen_day_menu_slots_facility_id_fkey")

    drop_if_exists unique_index(:kitchen_day_menu_slots, [:facility_id, :day_menu_id, :category],
                     name: "kitchen_day_menu_slots_unique_slot_index"
                   )

    drop table(:kitchen_day_menu_slots)

    drop table(:kitchen_day_menus_versions)

    drop constraint(
           :kitchen_resident_diet_profiles_versions,
           "kitchen_resident_diet_profiles_versions_version_source_id_fkey"
         )

    drop table(:kitchen_resident_diet_profiles_versions)

    drop constraint(
           :kitchen_products_versions,
           "kitchen_products_versions_version_source_id_fkey"
         )

    drop table(:kitchen_products_versions)

    drop constraint(
           :kitchen_menu_templates_versions,
           "kitchen_menu_templates_versions_version_source_id_fkey"
         )

    drop table(:kitchen_menu_templates_versions)

    drop constraint(:kitchen_products, "kitchen_products_facility_id_fkey")

    drop_if_exists unique_index(:kitchen_products, [:facility_id, :category, :name],
                     name: "kitchen_products_unique_name_per_facility_per_category_index"
                   )

    alter table(:kitchen_products) do
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :is_default
      remove :kcal
      remove :allergens
      remove :category
      remove :name
      remove :facility_id
    end

    drop constraint(:kitchen_menu_template_slots, "kitchen_menu_template_slots_product_id_fkey")

    alter table(:kitchen_menu_template_slots) do
      modify :product_id, :uuid
    end

    drop table(:kitchen_products)

    drop constraint(
           :kitchen_resident_diet_profiles,
           "kitchen_resident_diet_profiles_facility_id_fkey"
         )

    drop constraint(
           :kitchen_resident_diet_profiles,
           "kitchen_resident_diet_profiles_resident_id_fkey"
         )

    drop_if_exists unique_index(:kitchen_resident_diet_profiles, [:facility_id, :resident_id],
                     name: "kitchen_resident_diet_profiles_unique_resident_profile_index"
                   )

    drop table(:kitchen_resident_diet_profiles)

    drop constraint(:kitchen_menu_templates, "kitchen_menu_templates_facility_id_fkey")

    drop_if_exists unique_index(:kitchen_menu_templates, [:facility_id],
                     name: "kitchen_menu_templates_one_active_per_facility_index"
                   )

    alter table(:kitchen_menu_templates) do
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :is_active
      remove :name
      remove :facility_id
    end

    drop constraint(
           :kitchen_menu_template_slots,
           "kitchen_menu_template_slots_menu_template_id_fkey"
         )

    alter table(:kitchen_menu_template_slots) do
      modify :menu_template_id, :uuid
    end

    drop table(:kitchen_menu_templates)

    drop constraint(:kitchen_menu_template_slots, "kitchen_menu_template_slots_facility_id_fkey")

    drop_if_exists unique_index(
                     :kitchen_menu_template_slots,
                     [:facility_id, :menu_template_id, :day_of_week, :category],
                     name: "kitchen_menu_template_slots_unique_slot_index"
                   )

    drop table(:kitchen_menu_template_slots)
  end
end
