defmodule Caredeck.Repo.Migrations.AddFormfixApplicationNotes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:formfix_application_notes_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :facility_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:formfix_application_notes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:formfix_application_notes_versions) do
      modify :version_source_id,
             references(:formfix_application_notes,
               column: :id,
               name: "formfix_application_notes_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:formfix_application_notes) do
      add :facility_id,
          references(:facilities,
            column: :id,
            name: "formfix_application_notes_facility_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :application_id,
          references(:formfix_applications,
            column: :id,
            name: "formfix_application_notes_application_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :author_team_id,
          references(:team_identities,
            column: :id,
            name: "formfix_application_notes_author_team_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :body, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create index(:formfix_application_notes, [:facility_id, :application_id, :inserted_at])
  end

  def down do
    drop index(:formfix_application_notes, [:facility_id, :application_id, :inserted_at])

    drop constraint(:formfix_application_notes, "formfix_application_notes_facility_id_fkey")

    drop constraint(:formfix_application_notes, "formfix_application_notes_application_id_fkey")

    drop constraint(:formfix_application_notes, "formfix_application_notes_author_team_id_fkey")

    alter table(:formfix_application_notes) do
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :body
      remove :author_team_id
      remove :application_id
      remove :facility_id
    end

    drop constraint(
           :formfix_application_notes_versions,
           "formfix_application_notes_versions_version_source_id_fkey"
         )

    alter table(:formfix_application_notes_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:formfix_application_notes)

    drop table(:formfix_application_notes_versions)
  end
end
