defmodule Caredeck.Repo.Migrations.FlipFacilityTimezoneDefault do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:facilities) do
      modify :timezone, :text, default: "Etc/UTC"
    end

    execute("UPDATE facilities SET timezone = 'Etc/UTC' WHERE timezone = 'Europe/Berlin'")
  end

  def down do
    alter table(:facilities) do
      modify :timezone, :text, default: "Europe/Berlin"
    end
  end
end
