defmodule Caredeck.Repo.Migrations.InstallOrg do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:wards_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:wards, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:wards_versions) do
      modify :version_source_id,
             references(:wards,
               column: :id,
               name: "wards_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:wards) do
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :facility_id, :uuid, null: false
    end

    create table(:facility_memberships_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:facility_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:facility_memberships_versions) do
      modify :version_source_id,
             references(:facility_memberships,
               column: :id,
               name: "facility_memberships_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:facility_memberships) do
      add :role, :text, null: false
      add :source, :text, default: "manual"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :facility_id, :uuid, null: false
      add :user_id, :uuid
      add :team_identity_id, :uuid
    end

    create unique_index(:facility_memberships, [:team_identity_id, :facility_id],
             name: "facility_memberships_unique_team_facility_index"
           )

    create unique_index(:facility_memberships, [:user_id, :facility_id],
             name: "facility_memberships_unique_user_facility_index"
           )

    create table(:facilities_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:facilities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:wards) do
      modify :facility_id,
             references(:facilities,
               column: :id,
               name: "wards_facility_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:facility_memberships) do
      modify :facility_id,
             references(:facilities,
               column: :id,
               name: "facility_memberships_facility_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "facility_memberships_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :team_identity_id,
             references(:team_identities,
               column: :id,
               name: "facility_memberships_team_identity_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:facilities_versions) do
      modify :version_source_id,
             references(:facilities,
               column: :id,
               name: "facilities_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:facilities) do
      add :name, :text, null: false
      add :slug, :citext, null: false
      add :timezone, :text, default: "Europe/Berlin"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :district_id, :uuid, null: false
    end

    create unique_index(:facilities, [:slug], name: "facilities_unique_slug_index")

    create table(:districts_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:districts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:facilities) do
      modify :district_id,
             references(:districts,
               column: :id,
               name: "facilities_district_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:districts_versions) do
      modify :version_source_id,
             references(:districts,
               column: :id,
               name: "districts_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:districts) do
      add :name, :text, null: false
      add :slug, :citext, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:districts, [:slug], name: "districts_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:districts, [:slug], name: "districts_unique_slug_index")

    alter table(:districts) do
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :slug
      remove :name
    end

    drop constraint(:districts_versions, "districts_versions_version_source_id_fkey")

    alter table(:districts_versions) do
      modify :version_source_id, :uuid
    end

    drop constraint(:facilities, "facilities_district_id_fkey")

    alter table(:facilities) do
      modify :district_id, :uuid
    end

    drop table(:districts)

    drop table(:districts_versions)

    drop_if_exists unique_index(:facilities, [:slug], name: "facilities_unique_slug_index")

    alter table(:facilities) do
      remove :district_id
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :timezone
      remove :slug
      remove :name
    end

    drop constraint(:facilities_versions, "facilities_versions_version_source_id_fkey")

    alter table(:facilities_versions) do
      modify :version_source_id, :uuid
    end

    drop constraint(:facility_memberships, "facility_memberships_facility_id_fkey")

    drop constraint(:facility_memberships, "facility_memberships_user_id_fkey")

    drop constraint(:facility_memberships, "facility_memberships_team_identity_id_fkey")

    alter table(:facility_memberships) do
      modify :team_identity_id, :uuid
      modify :user_id, :uuid
      modify :facility_id, :uuid
    end

    drop constraint(:wards, "wards_facility_id_fkey")

    alter table(:wards) do
      modify :facility_id, :uuid
    end

    drop table(:facilities)

    drop table(:facilities_versions)

    drop_if_exists unique_index(:facility_memberships, [:user_id, :facility_id],
                     name: "facility_memberships_unique_user_facility_index"
                   )

    drop_if_exists unique_index(:facility_memberships, [:team_identity_id, :facility_id],
                     name: "facility_memberships_unique_team_facility_index"
                   )

    alter table(:facility_memberships) do
      remove :team_identity_id
      remove :user_id
      remove :facility_id
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :source
      remove :role
    end

    drop constraint(
           :facility_memberships_versions,
           "facility_memberships_versions_version_source_id_fkey"
         )

    alter table(:facility_memberships_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:facility_memberships)

    drop table(:facility_memberships_versions)

    alter table(:wards) do
      remove :facility_id
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :name
    end

    drop constraint(:wards_versions, "wards_versions_version_source_id_fkey")

    alter table(:wards_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:wards)

    drop table(:wards_versions)
  end
end
