defmodule Caredeck.Repo.Migrations.AddSectionAnswers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:aid_section_answers_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :facility_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:aid_section_answers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:aid_section_answers_versions) do
      modify :version_source_id,
             references(:aid_section_answers,
               column: :id,
               name: "aid_section_answers_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:aid_section_answers) do
      add :facility_id,
          references(:facilities,
            column: :id,
            name: "aid_section_answers_facility_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :application_id,
          references(:aid_applications,
            column: :id,
            name: "aid_section_answers_application_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :section_key, :text, null: false
      add :field_key, :text, null: false
      add :value_text, :text
      add :value_date, :date
      add :value_bool, :boolean
      add :value_decimal, :decimal
      add :value_atom, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(
             :aid_section_answers,
             [:facility_id, :application_id, :section_key, :field_key],
             name: "aid_section_answers_one_answer_per_field_index"
           )
  end

  def down do
    drop constraint(:aid_section_answers, "aid_section_answers_facility_id_fkey")

    drop constraint(:aid_section_answers, "aid_section_answers_application_id_fkey")

    drop_if_exists unique_index(
                     :aid_section_answers,
                     [:facility_id, :application_id, :section_key, :field_key],
                     name: "aid_section_answers_one_answer_per_field_index"
                   )

    alter table(:aid_section_answers) do
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :value_atom
      remove :value_decimal
      remove :value_bool
      remove :value_date
      remove :value_text
      remove :field_key
      remove :section_key
      remove :application_id
      remove :facility_id
    end

    drop constraint(
           :aid_section_answers_versions,
           "aid_section_answers_versions_version_source_id_fkey"
         )

    alter table(:aid_section_answers_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:aid_section_answers)

    drop table(:aid_section_answers_versions)
  end
end
