defmodule Caredeck.Repo.Migrations.InstallTeamIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:team_tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    create table(:team_identities_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:team_identities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:team_identities_versions) do
      modify :version_source_id,
             references(:team_identities,
               column: :id,
               name: "team_identities_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:team_identities) do
      add :facility_id, :uuid, null: false
      add :name, :text, null: false
      add :handle, :citext, null: false
      add :hashed_password, :text, null: false
      add :role_kind, :text, default: "care"
      add :avatar_url, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:team_identities, [:handle], name: "team_identities_unique_handle_index")
  end

  def down do
    drop_if_exists unique_index(:team_identities, [:handle],
                     name: "team_identities_unique_handle_index"
                   )

    alter table(:team_identities) do
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :avatar_url
      remove :role_kind
      remove :hashed_password
      remove :handle
      remove :name
      remove :facility_id
    end

    drop constraint(:team_identities_versions, "team_identities_versions_version_source_id_fkey")

    alter table(:team_identities_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:team_identities)

    drop table(:team_identities_versions)

    drop table(:team_tokens)
  end
end
