defmodule Caredeck.Repo.Migrations.AddServicesModule do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:service_messages_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :facility_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:service_requests_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :facility_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:service_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:service_requests_versions) do
      modify :version_source_id,
             references(:service_requests,
               column: :id,
               name: "service_requests_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:service_requests) do
      add :facility_id,
          references(:facilities,
            column: :id,
            name: "service_requests_facility_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :provider_id, :uuid, null: false
      add :resident_id, :uuid
      add :requester_user_id, :uuid
      add :requester_team_id, :uuid
      add :subkind, :text, null: false
      add :summary, :text
      add :payload, :map, default: %{}
      add :state, :text, null: false, default: "open"
      add :resolved_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create table(:service_providers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:service_requests) do
      modify :provider_id,
             references(:service_providers,
               column: :id,
               name: "service_requests_provider_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )

      modify :resident_id,
             references(:residents,
               column: :id,
               name: "service_requests_resident_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :requester_user_id,
             references(:users,
               column: :id,
               name: "service_requests_requester_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :requester_team_id,
             references(:team_identities,
               column: :id,
               name: "service_requests_requester_team_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:service_providers) do
      add :facility_id,
          references(:facilities,
            column: :id,
            name: "service_providers_facility_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :kind, :text, null: false
      add :name, :text, null: false
      add :display_name, :text
      add :contact_email, :text
      add :contact_phone, :text
      add :response_window_label, :text
      add :response_time_target_hours, :bigint
      add :is_internal, :boolean, default: false

      add :team_identity_id,
          references(:team_identities,
            column: :id,
            name: "service_providers_team_identity_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:service_providers, [:facility_id, :kind],
             name: "service_providers_one_per_kind_per_facility_index"
           )

    create table(:service_providers_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :facility_id, :uuid, null: false

      add :version_source_id,
          references(:service_providers,
            column: :id,
            name: "service_providers_versions_version_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:attachments) do
      modify :post_id, :uuid, null: true

      add :service_request_id,
          references(:service_requests,
            column: :id,
            name: "attachments_service_request_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :service_message_id, :uuid
    end

    create table(:service_messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:service_messages_versions) do
      modify :version_source_id,
             references(:service_messages,
               column: :id,
               name: "service_messages_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:attachments) do
      modify :service_message_id,
             references(:service_messages,
               column: :id,
               name: "attachments_service_message_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:service_messages) do
      add :facility_id,
          references(:facilities,
            column: :id,
            name: "service_messages_facility_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :service_request_id,
          references(:service_requests,
            column: :id,
            name: "service_messages_service_request_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :author_user_id,
          references(:users,
            column: :id,
            name: "service_messages_author_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :author_team_id,
          references(:team_identities,
            column: :id,
            name: "service_messages_author_team_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :body, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end
  end

  def down do
    drop constraint(:service_messages, "service_messages_facility_id_fkey")

    drop constraint(:service_messages, "service_messages_service_request_id_fkey")

    drop constraint(:service_messages, "service_messages_author_user_id_fkey")

    drop constraint(:service_messages, "service_messages_author_team_id_fkey")

    alter table(:service_messages) do
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :body
      remove :author_team_id
      remove :author_user_id
      remove :service_request_id
      remove :facility_id
    end

    drop constraint(:attachments, "attachments_service_message_id_fkey")

    alter table(:attachments) do
      modify :service_message_id, :uuid
    end

    drop constraint(
           :service_messages_versions,
           "service_messages_versions_version_source_id_fkey"
         )

    alter table(:service_messages_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:service_messages)

    drop constraint(:attachments, "attachments_service_request_id_fkey")

    alter table(:attachments) do
      remove :service_message_id
      remove :service_request_id
      modify :post_id, :uuid, null: false
    end

    drop constraint(
           :service_providers_versions,
           "service_providers_versions_version_source_id_fkey"
         )

    drop table(:service_providers_versions)

    drop constraint(:service_providers, "service_providers_facility_id_fkey")

    drop constraint(:service_providers, "service_providers_team_identity_id_fkey")

    drop_if_exists unique_index(:service_providers, [:facility_id, :kind],
                     name: "service_providers_one_per_kind_per_facility_index"
                   )

    alter table(:service_providers) do
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :team_identity_id
      remove :is_internal
      remove :response_time_target_hours
      remove :response_window_label
      remove :contact_phone
      remove :contact_email
      remove :display_name
      remove :name
      remove :kind
      remove :facility_id
    end

    drop constraint(:service_requests, "service_requests_provider_id_fkey")

    drop constraint(:service_requests, "service_requests_resident_id_fkey")

    drop constraint(:service_requests, "service_requests_requester_user_id_fkey")

    drop constraint(:service_requests, "service_requests_requester_team_id_fkey")

    alter table(:service_requests) do
      modify :requester_team_id, :uuid
      modify :requester_user_id, :uuid
      modify :resident_id, :uuid
      modify :provider_id, :uuid
    end

    drop table(:service_providers)

    drop constraint(:service_requests, "service_requests_facility_id_fkey")

    alter table(:service_requests) do
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :resolved_at
      remove :state
      remove :payload
      remove :summary
      remove :subkind
      remove :requester_team_id
      remove :requester_user_id
      remove :resident_id
      remove :provider_id
      remove :facility_id
    end

    drop constraint(
           :service_requests_versions,
           "service_requests_versions_version_source_id_fkey"
         )

    alter table(:service_requests_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:service_requests)

    drop table(:service_requests_versions)

    drop table(:service_messages_versions)
  end
end
