defmodule Caredeck.Repo.Migrations.InstallNotifications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:notifications_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :facility_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:notifications, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:notifications_versions) do
      modify :version_source_id,
             references(:notifications,
               column: :id,
               name: "notifications_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:notifications) do
      add :facility_id,
          references(:facilities,
            column: :id,
            name: "notifications_facility_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "notifications_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :actor_kind, :text, null: false
      add :actor_id, :uuid, null: false
      add :verb, :text, null: false
      add :target_kind, :text, null: false
      add :target_id, :uuid, null: false
      add :thumbnail_url, :text
      add :read_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(
             :notifications,
             [:facility_id, :user_id, :actor_kind, :actor_id, :verb, :target_kind, :target_id],
             name: "notifications_unique_event_per_user_index"
           )
  end

  def down do
    drop constraint(:notifications, "notifications_facility_id_fkey")

    drop constraint(:notifications, "notifications_user_id_fkey")

    drop_if_exists unique_index(
                     :notifications,
                     [
                       :facility_id,
                       :user_id,
                       :actor_kind,
                       :actor_id,
                       :verb,
                       :target_kind,
                       :target_id
                     ],
                     name: "notifications_unique_event_per_user_index"
                   )

    alter table(:notifications) do
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :read_at
      remove :thumbnail_url
      remove :target_id
      remove :target_kind
      remove :verb
      remove :actor_id
      remove :actor_kind
      remove :user_id
      remove :facility_id
    end

    drop constraint(:notifications_versions, "notifications_versions_version_source_id_fkey")

    alter table(:notifications_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:notifications)

    drop table(:notifications_versions)
  end
end
