defmodule Caredeck.Repo.Migrations.InstallRelativeInvitations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:relative_invitations_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :facility_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:relative_invitations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:relative_invitations_versions) do
      modify :version_source_id,
             references(:relative_invitations,
               column: :id,
               name: "relative_invitations_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:relative_invitations) do
      add :facility_id,
          references(:facilities,
            column: :id,
            name: "relative_invitations_facility_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :inviter_user_id,
          references(:users,
            column: :id,
            name: "relative_invitations_inviter_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :resident_id,
          references(:residents,
            column: :id,
            name: "relative_invitations_resident_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :email, :citext, null: false
      add :suggested_relationship, :text
      add :token, :text
      add :expires_at, :utc_datetime_usec, null: false
      add :accepted_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:relative_invitations, [:facility_id, :resident_id, :email],
             name: "relative_invitations_unique_pending_per_resident_email_index",
             where: "(accepted_at IS NULL)"
           )
  end

  def down do
    drop constraint(:relative_invitations, "relative_invitations_facility_id_fkey")

    drop constraint(:relative_invitations, "relative_invitations_inviter_user_id_fkey")

    drop constraint(:relative_invitations, "relative_invitations_resident_id_fkey")

    drop_if_exists unique_index(:relative_invitations, [:facility_id, :resident_id, :email],
                     name: "relative_invitations_unique_pending_per_resident_email_index"
                   )

    alter table(:relative_invitations) do
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :accepted_at
      remove :expires_at
      remove :token
      remove :suggested_relationship
      remove :email
      remove :resident_id
      remove :inviter_user_id
      remove :facility_id
    end

    drop constraint(
           :relative_invitations_versions,
           "relative_invitations_versions_version_source_id_fkey"
         )

    alter table(:relative_invitations_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:relative_invitations)

    drop table(:relative_invitations_versions)
  end
end
